language: python

python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install coveralls
# command to run tests
script: 
  - tox
after_success:
  coveralls

sudo: false
cache: pip
